### ISSUE TITLE
Can't combine variables when attributes are different

### ISSUE THREAD

**Issue by mara-freilich** [intake/intake-esm#157] opened 2019-10-17 18:25 UTC
I am trying to load both DIC (dissic) and cell thickness (thkcello) from all of the models that have those and am running into an issue with the UK model where these variables can't be merged because the attributes are different. The 'realm' is 'ocean' for thkcello but 'ocnBgchem' for dissic. 

It seems like this could be solved by relaxing the requirements that the attributes are the same for each variable.

The error that I get is: MergeError: conflicting values for variable 'vertices_longitude' on objects to be combined. You can skip this check by specifying compat='override'.

The code I am running: 
```python
cat = col.search(experiment_id=['historical'], table_id='Oyr', variable_id=['dissic','thkcello'], grid_label='gn')
uni_dict = col.unique(['source_id', 'experiment_id', 'table_id'])

models = set(uni_dict['source_id']['values']) # all the models

for experiment_id in ['historical']:
    query = dict(experiment_id=experiment_id, table_id='Omon', 
                 variable_id=['dissic','thkcello'], grid_label='gn')  
    cat = col.search(**query)
    models = models.intersection({model for model in cat.df.source_id.unique().tolist()})

models = list(models)

cat = col.search(experiment_id=['historical'], table_id='Omon', 
                 variable_id=['dissic','thkcello'], grid_label='gn', source_id=models)

dset_dict = cat.to_dataset_dict(zarr_kwargs={'consolidated': True, 'decode_times': False}, 
                                cdf_kwargs={'chunks': {'time' : 20}, 'decode_times': False})
```

**Comment by andersy005** [comment] 2019-10-17 21:29
@mfreilich1, 

Are you using the CMIP6 data in the cloud or on NCAR's Glade?

**Comment by mfreilich1** [comment] 2019-10-17 21:30
I am using the data on the cloud

**Comment by andersy005** [comment] 2019-10-17 21:44
Great! I will look into this, and will get back you once I find something promising :)

**Comment by Recalculate** [comment] 2020-07-07 10:40
Any progress on this, I'm getting exactly the same errors....

**Comment by andersy005** [comment] 2020-07-07 18:15
@Recalculate, 

When you get a chance, can you post a traceback of the error you are getting? I am asking because I tried @mara-freilich's code snippet, and I got a different type of error:

```python
/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/dataset.py in _reindex(self, indexers, method, tolerance, copy, fill_value, sparse, **indexers_kwargs)
   2517             raise ValueError("invalid reindex dimensions: %s" % bad_dims)
   2518 
-> 2519         variables, indexes = alignment.reindex_variables(
   2520             self.variables,
   2521             self.sizes,

/srv/conda/envs/notebook/lib/python3.8/site-packages/xarray/core/alignment.py in reindex_variables(variables, sizes, indexes, indexers, method, tolerance, copy, fill_value, sparse)
    545 
    546             if not index.is_unique:
--> 547                 raise ValueError(
    548                     "cannot reindex or align along dimension %r because the "
    549                     "index has duplicate values" % dim

ValueError: cannot reindex or align along dimension 'deptht' because the index has duplicate values
```

**Comment by Recalculate** [comment] 2020-07-08 09:43
No problems.  Here is the traceback:

`MergeError                                Traceback (most recent call last)
<ipython-input-5-f04e8fed5487> in <module>
----> 1 dset_dict_thetaso = cat.to_dataset_dict(zarr_kwargs={'consolidated': True, 'decode_times': True},cdf_kwargs={'chunks': {}, 'decode_times': True})
      2 dset_dict_thetaso.keys()
      3 
      4 #dset_dict_bgc = cat3.to_dataset_dict(zarr_kwargs={'consolidated': True, 'decode_times': True},cdf_kwargs={'chunks': {}, 'decode_times': True})
      5 #dset_dict_bgc.keys()

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/core.py in to_dataset_dict(self, zarr_kwargs, cdf_kwargs, preprocess, storage_options, progressbar)
    628 
    629             for i, task in enumerate(concurrent.futures.as_completed(future_tasks)):
--> 630                 ds = task.result()
    631                 self._datasets[ds.attrs['intake_esm_dataset_key']] = ds
    632                 if self.progressbar:

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    423                 raise CancelledError()
    424             elif self._state == FINISHED:
--> 425                 return self.__get_result()
    426 
    427             self._condition.wait(timeout)

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/core.py in _load_source(source)
    616 
    617         def _load_source(source):
--> 618             return source.to_dask()
    619 
    620         sources = [source(**source_kwargs) for _, source in self.items()]

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/source.py in to_dask(self)
    120     def to_dask(self):
    121         """Return xarray object (which will have chunks)"""
--> 122         self._load_metadata()
    123         return self._ds
    124 

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake/source/base.py in _load_metadata(self)
    124         """load metadata only if needed"""
    125         if self._schema is None:
--> 126             self._schema = self._get_schema()
    127             self.datashape = self._schema.datashape
    128             self.dtype = self._schema.dtype

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/source.py in _get_schema(self)
     83 
     84         if self._ds is None:
---> 85             self._open_dataset()
     86 
     87             metadata = {

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/source.py in _open_dataset(self)
    112             self.zarr_kwargs,
    113             self.cdf_kwargs,
--> 114             self.preprocess,
    115         )
    116         ds.attrs['intake_esm_dataset_key'] = self.key

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/merge_util.py in _aggregate(aggregation_dict, agg_columns, n_agg, v, lookup, mapper_dict, zarr_kwargs, cdf_kwargs, preprocess)
    227         return ds
    228 
--> 229     return apply_aggregation(v)
    230 
    231 

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/merge_util.py in apply_aggregation(v, agg_column, key, level)
    218                 f'Merging {len(dsets)} dataset(s) into a single Dataset with options={agg_options}.\ndsets={dsets}'
    219             )
--> 220             ds = union(dsets, options=agg_options)
    221 
    222         ds.attrs = attrs

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/merge_util.py in union(dsets, options)
    105     except Exception as exc:
    106         logger.error('Failed to merge datasets.')
--> 107         raise exc
    108 
    109 

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/merge_util.py in union(dsets, options)
    102     options = options or {}
    103     try:
--> 104         return xr.merge(dsets, **options)
    105     except Exception as exc:
    106         logger.error('Failed to merge datasets.')

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/core/merge.py in merge(objects, compat, join, fill_value)
    791         dict_like_objects.append(obj)
    792 
--> 793     merge_result = merge_core(dict_like_objects, compat, join, fill_value=fill_value)
    794     merged = Dataset._construct_direct(**merge_result._asdict())
    795     return merged

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/core/merge.py in merge_core(objects, compat, join, priority_arg, explicit_coords, indexes, fill_value)
    553 
    554     prioritized = _get_priority_vars_and_indexes(aligned, priority_arg, compat=compat)
--> 555     variables, out_indexes = merge_collected(collected, prioritized, compat=compat)
    556     assert_unique_multiindex_level_names(variables)
    557 

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/core/merge.py in merge_collected(grouped, prioritized, compat)
    226                 variables = [variable for variable, _ in elements_list]
    227                 try:
--> 228                     merged_vars[name] = unique_variable(name, variables, compat)
    229                 except MergeError:
    230                     if compat != "minimal":

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/core/merge.py in unique_variable(name, variables, compat, equals)
    141     if not equals:
    142         raise MergeError(
--> 143             f"conflicting values for variable {name!r} on objects to be combined. "
    144             "You can skip this check by specifying compat='override'."
    145         )

MergeError: conflicting values for variable 'latitude' on objects to be combined. You can skip this check by specifying compat='override'.`

**Comment by Recalculate** [comment] 2020-07-09 14:35
Some advice on this really would be appreciated.

**Comment by andersy005** [comment] 2020-07-09 16:26
Thank you for your patience, @Recalculate! 

Can you post the code your are using? I'd like to see if I can reproduce your issue, and come up with a fix as well.

**Comment by Recalculate** [comment] 2020-07-09 20:56
Ta, code below should do the trick.  You can get these datasets to merge by intaking each separately (thetao and so are fine, it is vmo that is the issue) and then using merge and the compat='override' option, but I can't see a way of applying this option in to_dataset_dict.  Similar issues are encountered when trying to merge the 'o2' variable with 'thetao' or 'so'.  

`!pip install intake-esm --upgrade
!pip install cmip6_preprocessing

import intake
import xarray as xr

col_url='https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json'
col = intake.open_esm_datastore(col_url)
cat = col.search(require_all_on=["source_id"],experiment_id=['ssp585'],table_id='Omon',variable_id=['thetao','so','vmo'],grid_label='gn')

dset_dict_thetaso = cat.to_dataset_dict(zarr_kwargs={'consolidated': True, 'decode_times': True},cdf_kwargs={'chunks': {}, 'decode_times': True})
`

**Comment by andersy005** [comment] 2020-07-10 00:33
@Recalculate, 

Here's a **temporary workaround**:

- modify the "merge" aggregation options

```python
col = intake.open_esm_datastore(col_url)
col.aggregation_info['aggregations'][0].update({'options': {'compat': 'override'}})
```

Once the aggregations have been updated, things appear to be working

```python
cat = col.search(require_all_on=["source_id"],experiment_id=['ssp585'],table_id='Omon',variable_id=['thetao','so','vmo'],grid_label='gn')

dset_dict_thetaso = cat.to_dataset_dict(zarr_kwargs={'consolidated': True, 'decode_times': True})
```


I am going to look into a permanent solution that would allow users to easily modify the aggregations, and will post an update here once I have a working solution.

**Comment by Recalculate** [comment] 2020-07-10 14:54
Thanks, that did the trick!

**Comment by andersy005** [comment] 2020-11-24 20:02
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue with the latest stable version(v2020.11.4)

**Closed by andersy005** 2020-11-24 20:02 UTC
Labels: awaiting more information

**Comment by Recalculate** [comment] 2021-01-12 10:22
Hi folks.  Sorry to resurrect an old thread, but it does seem that the workaround no longer is recognised by the newer versions.  Now it throws: AttributeError: aggregation_info 

I can still get things to work by rolling back to older versions, but this is obviously suboptimal.  Is there a way to turn on compat: override in the new version?

**Comment by andersy005** [comment] 2021-01-12 15:30
@Recalculate, thank you for the report! Do you have a reproducible example I can use to figure out what's going on?

**Comment by Recalculate** [comment] 2021-01-12 16:06
Sure:  
`
import intake
col_url='https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json'
col = intake.open_esm_datastore(col_url)
col.aggregation_info['aggregations'][0].update({'options': {'compat': 'override'}})
`

Should do the trick.

**Comment by andersy005** [comment] 2021-01-12 16:24
Which version of intake-esm are you using? 

```python
In [12]: import intake_esm

In [13]: intake_esm.show_versions()

INSTALLED VERSIONS
------------------

cftime: 1.3.0
dask: 2020.12.0
fastprogress: 0.2.7
fsspec: 0.8.5
gcsfs: 0.7.1
intake: 0.6.0
intake_esm: 2020.12.18
netCDF4: 1.5.5.1
pandas: 1.2.0
requests: 2.25.1
s3fs: 0.5.2
xarray: 0.16.2
zarr: 2.6.1
```


I am on `2020.12.18` and this line doesn't work `col.aggregation_info['aggregations'][0].update({'options': {'compat': 'override'}})`

**Comment by Recalculate** [comment] 2021-01-13 09:32
Hmm, all my versions are much older: 
intake                  0.5.3              
intake-esm              2019.10.15.post90
I'll update and have a play around to see if I can improve things.  Thans!

**Comment by jdldeauna** [comment] 2021-04-21 22:44
Hello! I'm encountering similar errors, even with updated versions of intake:

``` python 
intake: 0.6.2
intake_esm: 2021.1.15
```

Example:

``` python
import intake_esm
import intake
from cmip6_preprocessing.preprocessing import combined_preprocessing

cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6-noQC.json"
col = intake.open_esm_datastore(cat_url)
    
cat = col.search(table_id='Omon', activity_id='CMIP',
                 experiment_id='historical',
                 variable_id=['uo','vo'], 
                 grid_label='gn', 
                 member_id='r1i1p1f1',
                 source_id='MPI-ESM1-2-HR'
                )
cmip6_compiled = cat.to_dataset_dict(
            zarr_kwargs={'consolidated':True, 'decode_times': True, 'use_cftime': True},
            preprocess=combined_preprocessing
            )
```
Errors:

``` python
~/miniconda3/envs/cartopy_env/lib/python3.8/site-packages/xarray/core/merge.py in merge_collected(grouped, prioritized, compat)
    228                 try:
--> 229                     merged_vars[name] = unique_variable(name, variables, compat)
    230                 except MergeError:

~/miniconda3/envs/cartopy_env/lib/python3.8/site-packages/xarray/core/merge.py in unique_variable(name, variables, compat, equals)
    140     if not equals:
--> 141         raise MergeError(
    142             f"conflicting values for variable {name!r} on objects to be combined. "

MergeError: conflicting values for variable 'lat' on objects to be combined. You can skip this check by specifying compat='override'.

The above exception was the direct cause of the following exception:

AggregationError: 
        Failed to merge multiple datasets in group with key=CMIP.MPI-M.MPI-ESM1-2-HR.historical.Omon.gn into a single xarray Dataset as variables.

        *** Arguments passed to xarray.merge() ***:

        - objs: a list of 2 datasets
        - kwargs: {}
```

Using ` col.aggregation_info['aggregations'][0].update({'options': {'compat': 'override'}})` results in the following error:

``` python
TypeError                                 Traceback (most recent call last)
<ipython-input-2-acc455e75336> in <module>
      6 col = intake.open_esm_datastore(cat_url)
      7 
----> 8 col.aggregation_info['aggregations'][0].update({'options': {'compat': 'override'}})
      9 
     10 cat = col.search(table_id='Omon', activity_id='CMIP',

TypeError: tuple indices must be integers or slices, not str
```

**Comment by jdldeauna** [comment] 2021-06-07 16:50
Just in case other people encounter a similar error, cmip6_preprocessing has [new features](https://cmip6-preprocessing.readthedocs.io/en/latest/postprocessing.html) which address the issue:

```python
import intake_esm
import intake
from cmip6_preprocessing.preprocessing import combined_preprocessing

cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6-noQC.json"
col = intake.open_esm_datastore(cat_url)

kwargs = {
    'zarr_kwargs':{
        'consolidated':True,
        'use_cftime':True
    },
    'aggregate':False,
    'preprocess':combined_preprocessing
}

cat = col.search(experiment_id='historical',
                 variable_id=['uo','vo','so'], 
                 grid_label='gn', 
                 member_id='r1i1p1f1',
                 source_id='MPI-ESM1-2-HR'
                )
ddict = cat.to_dataset_dict(**kwargs)
list(ddict.keys())

from cmip6_preprocessing.postprocessing import merge_variables

ddict_merged = merge_variables(ddict)
list(ddict_merged.keys())

ddict_merged['MPI-ESM1-2-HR.gn.historical.Omon.r1i1p1f1']

from cmip6_preprocessing.postprocessing import concat_members

ddict_concat = concat_members(ddict_merged)
print(list(ddict_concat.keys()))
ddict_concat['MPI-ESM1-2-HR.gn.historical.Omon']

ds = ddict_concat['MPI-ESM1-2-HR.gn.historical.Omon']

ds.so
```

**Comment by Recalculate** [comment] 2021-07-22 13:43
Trying the new merge_variable approach, I get the warning:

`/srv/conda/envs/notebook/lib/python3.8/site-packages/cmip6_preprocessing/postprocessing.py:122: UserWarning: ScenarioMIP.CCCma.CanESM5.ssp585.r10i1p2f1.Omon.gn.v20190429 failed to combine with :Unrecognised value for combine_attrs=drop_conflicts`

for each filename (filename changes for each warning obviously).  This means that I get an empty merged dataset at the end.  This happens if I run identical code to that you have listed.
